<?php if (Mage::getStoreConfig('speedextrack/speedextrack_general/enabled')) { ?>

    <div class = "block block-trackorder">
        <div class = "block-title">
            <strong><span>Track Order Here</span></strong>
        </div>
        <div class = "block-content">
            
                 <label for = "widget"><a target="_blank" href="<?php echo Mage::getBaseUrl() . 'speedextrack/index'; ?>"> Track Order</a></label>
            
        </div>
    </div>


<?php } ?>
